### ISSUE TITLE
Cannot load extension in EM

### ISSUE THREAD

**Issue by xperseguers** [AOEpeople/TYPO3_Restler#1]
When cloning the extension (in an attempt to allow future dev on it and pull requests), and after running `composer install`, the extension cannot be loaded in EM (6.2.16-dev) since it fails with:

```
#1382276561: The package "restler" depends on "luracast/restler" which is not present in the system
```

**Comment by vdespa** [comment]
Thank your for your report and your interest. We are aware of the bug and we are working on a solution to better integrate with the EM in TYPO3.

For development purposes the workaround would be to copy the source files from GitHub, to rename the composer.json in _composer.json (so that the EM does not execute it) and you should be able to run `COMPOSER=_composer.json composer install` inside the extension and include the generated autoloader file (from the vendors folder). 

Hope this helps.

**Comment by xperseguers** [comment]
Yes, that's basically what I did. Thanks. Another problem is the download of TYPO3 itself. Somehow I have the feeling that we would need two different composer.json files, one that is used by TYPO3 when running on composer, and possibly an "internal" one for the dependency to external libraries. Don't know how the composer team is willing to handle that, if you are on stack (https://forger.typo3.org for getting there), do not hesitate to join the #composer channel to discuss the problem and solution with other team members.

**Comment by vdespa** [comment]
Hi @xperseguers 

We managed to fix the issue by doing an composer install (without dev dependencies) before loading the extension in TER.

Starting with version 1.1.6 there should be no more errors when installing.

If you can test and confirm that it works on your side it would be great. If you encounter any other bugs / issues, feel free to open a new issue.
