### ISSUE TITLE
Can TYPO3_Restler handle label translation (xlf)?

### ISSUE THREAD

**Issue by tmotyl** [AOEpeople/TYPO3_Restler#13]
Is it possible to use translated labels (xlf) with reslter?
Can it detect language based on AcceptLanguage header?

**Comment by vdespa** [comment]
Hi @tmotyl 

1. Is it possible to use translated labels (xlf) with reslter?

Yes, because the language object is initialised in TYPO3. A simple test to see if it works would be to call inside the controller the LocalizationUtility.

    TYPO3\CMS\Extbase\Utility\LocalizationUtility::translate('LANGUAGE_KEY', 'EXTENSION');

2.  Can it detect language based on AcceptLanguage header?

Not sure. If you can configure TYPO3 to do it, it should work out of the box. There is not explicit functionality build into Restler to handle that. 

Thanks for your interest. Let us know if you have any other questions.

**Comment by tmotyl** [comment]
Hi @vdespa  
That works, thanks.
For the record:
I have tested it by faking L param in configuration class ```GeneralUtility::_GETset(1,'L');```
However It should also work with TS conditions on AcceptLanguage header.
And in api controller I'm calling 
```$this->loader->initializeFrontEndRendering($this->pid);```
before requesting language label.

It also worked with fetching from db translated extbase records.
