### ISSUE TITLE
TS-Configuration not fully loaded

### ISSUE THREAD

**Issue by hoswmph** [AOEpeople/TYPO3_Restler#17]
Calling ViewControllers via controllers in restler ext, the fe initialisation is not fully loaded.
E.g. configuration changes from templates are not reflected / parsed.
I already tried to leave the ext_localconf-import field empty.

My use case:
I'm calling the femanager NewViewController->createAction to create users via REST API using the `\TYPO3\CMS\Extbase\Mvc\Dispatcher` method.

**Comment by soda-2005** [comment]
If you can avoid it, you should not use REST-endpoints to render HTML...this is often a bad aproach. Sometimes you must be able to render URL's in REST-endpoints or you maybe must render a single tt_conent-element. For this reason, the restler-Extension contains the 'TYPO3-Loader' to initialize the TSFE....but you should not use it to render extBase-views (that's not the case, you should use restler for).

A REST-Endpoint is not an alternative to AJAX (which often returns HTML). By using a REST-Endpoint, you should be able to seperate layout/HTML from data (so your REST-endpoint should only return data/json, but not HTML).

We use REST-endpoints like this:
We render the HTML-structure by calling a normal TYPO3-page/URL. Also we load some JavaScript (angularJS) on that TYPO3-page. Than, when the user clicks on a link or some event happens, the JavaScript calls a REST-endpoint to do something (or load some data). After the REST-endpoint returned the data (JSON) the JavaScript (angularJS) use that data to modify/change the allready existing HTML-code in the browser.

So, if you want to render extBase-Views by restler: Do it and fix restler, so that it works. You can do a pull-request, when you have changed restler (so that it works). But than, we will take a look at the code and decide, if the code should go into restler or not. REST-endpoints by Restler should be fast and we avoid to 'load the full TYPO3-monster-Frontend' in restler (because FE-initialization in restler should be slim/fast). If the initializing of the TSFE is not fast/slim after your code-changes, we will not accept your pull-request (because it's not that way, you should use restler for).

Good luck by modifing restler for your requirements.

**Comment by hoswmph** [comment]
It's clear to me REST is not intended for HTML-Output - and in fact is not used for this in my case.
What I'm using is the createAction of FEManager extension, to create FEUsers via REST-Service, as stated in the issue report. Not all ViewController actions are also providing HTML-output...
You might want to have a look at the extension femanager and the mentioned controller flow, for a better understanding of my intended usage of the ViewController.
